"""
Gap analysis module
Identifies gaps between candidate qualifications and job requirements
"""

from typing import Dict, List
import logging

logger = logging.getLogger(__name__)


class GapAnalyzer:
    """Analyze gaps between candidate and job requirements"""

    def __init__(self):
        """Initialize gap analyzer"""
        pass

    def generate_report(self, job_posting: Dict, analysis: Dict,
                       customized_resume: str, cover_letter: str) -> str:
        """
        Generate comprehensive analysis report

        Args:
            job_posting: Parsed job posting data
            analysis: AI analysis results
            customized_resume: Customized resume text
            cover_letter: Customized cover letter text

        Returns:
            Markdown formatted report
        """
        company = job_posting.get('company', 'Unknown')
        position = job_posting.get('position', 'Unknown')
        location = job_posting.get('location', 'Not specified')
        job_type = job_posting.get('job_type', 'Not specified')
        salary = job_posting.get('salary', 'Not specified')

        report = f"""# Job Application Analysis Report

## Position Details

**Company:** {company}
**Position:** {position}
**Location:** {location}
**Job Type:** {job_type}
**Salary:** {salary}

---

## Match Analysis

**Overall Match Score:** {analysis.get('match_score', 0)}/100

### Your Strengths for This Role

{self._format_list(analysis.get('strengths', []))}

### Identified Gaps

{self._format_list(analysis.get('gaps', []) or ['No significant gaps identified!'])}

---

## Strategies to Address Gaps and Stand Out

{self._format_list(analysis.get('strategies', []))}

---

## Application Tips

{self._format_list(analysis.get('tips', []))}

---

## Job Requirements

### Required Qualifications
{self._format_list(job_posting.get('requirements', []) or ['Not specified'])}

### Preferred Qualifications
{self._format_list(job_posting.get('qualifications', []) or ['Not specified'])}

### Responsibilities
{self._format_list(job_posting.get('responsibilities', []) or ['Not specified'])}

---

## Application Materials Status

✓ Resume customized and ready
✓ Cover letter generated and ready
✓ Gap analysis complete

---

## Next Steps

1. **Review** your customized resume and cover letter
2. **Prepare** examples for identified strengths
3. **Research** the company culture and recent news
4. **Practice** addressing any gaps positively
5. **Apply** through the provided channels

"""

        # Add application links if available
        if job_posting.get('application_url'):
            report += f"\n### Apply Online\n{job_posting['application_url']}\n"

        if job_posting.get('application_email'):
            report += f"\n### Apply via Email\n{job_posting['application_email']}\n"

        report += "\n---\n\n*Generated by Job Application Automation System*"

        return report

    def _format_list(self, items: List[str]) -> str:
        """Format list items as markdown"""
        if not items:
            return "*None*"

        return '\n'.join(f"- {item}" for item in items)

    def create_quick_summary(self, analysis: Dict, job_posting: Dict) -> str:
        """
        Create a quick summary for easy reference

        Args:
            analysis: AI analysis results
            job_posting: Job posting data

        Returns:
            Brief summary text
        """
        company = job_posting.get('company', 'Unknown')
        position = job_posting.get('position', 'Unknown')
        score = analysis.get('match_score', 0)

        # Determine fit level
        if score >= 80:
            fit_level = "Excellent fit"
            emoji = "🌟"
        elif score >= 60:
            fit_level = "Good fit"
            emoji = "✓"
        elif score >= 40:
            fit_level = "Moderate fit"
            emoji = "~"
        else:
            fit_level = "Challenging fit"
            emoji = "!"

        summary = f"""{emoji} {fit_level} ({score}/100)

{company} - {position}

Top Strengths:
"""
        # Add top 3 strengths
        strengths = analysis.get('strengths', [])[:3]
        for strength in strengths:
            summary += f"  • {strength}\n"

        # Add main gap if any
        gaps = analysis.get('gaps', [])
        if gaps:
            summary += f"\nKey Gap to Address:\n  • {gaps[0]}\n"

        # Add top strategy
        strategies = analysis.get('strategies', [])
        if strategies:
            summary += f"\nMain Strategy:\n  • {strategies[0]}\n"

        return summary
